FROM openjdk:17-slim as builder
WORKDIR /app
COPY . .
RUN ./mvnw clean install -DskipTests

FROM openjdk:17
WORKDIR /app
COPY --from=builder /app/target/*.jar task-service.jar
EXPOSE 8081
CMD ["java", "-jar", "task-service.jar"]