FROM openjdk:17-slim as builder
WORKDIR /app
COPY . .
RUN ./mvnw clean install -DskipTests

FROM openjdk:17
WORKDIR /app
COPY --from=builder /app/target/*.jar auth-service.jar
EXPOSE 8087
CMD ["java", "-jar", "auth-service.jar"]