FROM openjdk:17-slim as builder
WORKDIR /app
COPY . .
RUN ./mvnw clean install -DskipTests

FROM openjdk:17
WORKDIR /app
COPY --from=builder /app/target/*.jar user-service.jar
EXPOSE 8086
CMD ["java", "-jar", "user-service.jar"]